"""empty message

Revision ID: 0842e999a163
Revises: 130953cf9cd3
Create Date: 2020-11-20 18:53:38.808720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0842e999a163'
down_revision = '130953cf9cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv', sa.Column('inv_type', sa.String(length=64), nullable=True))
    op.add_column('inv', sa.Column('remaining_balance', sa.Float(), nullable=True))
    op.add_column('inv', sa.Column('status', sa.String(length=64), nullable=True))
    op.alter_column('inv', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_inv_inv_type'), 'inv', ['inv_type'], unique=False)
    op.create_index(op.f('ix_inv_status'), 'inv', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inv_status'), table_name='inv')
    op.drop_index(op.f('ix_inv_inv_type'), table_name='inv')
    op.alter_column('inv', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('inv', 'status')
    op.drop_column('inv', 'remaining_balance')
    op.drop_column('inv', 'inv_type')
    # ### end Alembic commands ###
