"""empty message

Revision ID: 130953cf9cd3
Revises: be96089c4f31
Create Date: 2020-11-20 11:47:11.373439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130953cf9cd3'
down_revision = 'be96089c4f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=True)
    op.add_column('inv', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inv', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inv', type_='foreignkey')
    op.drop_column('inv', 'customer_id')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
