"""empty message

Revision ID: 149ac8d8520c
Revises: 889ff2995f88
Create Date: 2020-12-21 21:58:10.157400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149ac8d8520c'
down_revision = '889ff2995f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b1product', sa.Column('bulk_bulk_expense', sa.Float(), nullable=True))
    op.add_column('b1product', sa.Column('bulk_expense', sa.Float(), nullable=True))
    op.add_column('b1product', sa.Column('single_expense', sa.Float(), nullable=True))
    op.add_column('b2product', sa.Column('bulk_bulk_expense', sa.Float(), nullable=True))
    op.add_column('b2product', sa.Column('bulk_expense', sa.Float(), nullable=True))
    op.add_column('b2product', sa.Column('single_expense', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('b2product', 'single_expense')
    op.drop_column('b2product', 'bulk_expense')
    op.drop_column('b2product', 'bulk_bulk_expense')
    op.drop_column('b1product', 'single_expense')
    op.drop_column('b1product', 'bulk_expense')
    op.drop_column('b1product', 'bulk_bulk_expense')
    # ### end Alembic commands ###
