"""empty message

Revision ID: 16e5065ee545
Revises: a27d68c3df33
Create Date: 2021-01-09 10:55:00.778274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e5065ee545'
down_revision = 'a27d68c3df33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crtransaction', 'customer_id')
    op.add_column('customer', sa.Column('remaining_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'remaining_balance')
    op.add_column('crtransaction', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
