"""empty message

Revision ID: 341109fb89be
Revises: acc4d48379be
Create Date: 2020-11-30 12:24:39.730521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341109fb89be'
down_revision = 'acc4d48379be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inv', 'date')
    # ### end Alembic commands ###
