"""empty message

Revision ID: 3aeea2af3779
Revises: dc2954e971cb
Create Date: 2020-11-30 00:23:17.851988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeea2af3779'
down_revision = 'dc2954e971cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv', sa.Column('vat_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inv', 'vat_percentage')
    # ### end Alembic commands ###
