"""empty message

Revision ID: 8313b121a328
Revises: 289a675ac94b
Create Date: 2021-01-09 12:31:16.943267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8313b121a328'
down_revision = '289a675ac94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'crtransaction', 'customer', ['customer_id'], ['id'])
    op.add_column('customer', sa.Column('remaining_balance', sa.Float(), nullable=True))
    op.drop_constraint(None, 'revtransaction', type_='foreignkey')
    op.drop_column('revtransaction', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revtransaction', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'revtransaction', 'customer', ['customer_id'], ['id'])
    op.drop_column('customer', 'remaining_balance')
    op.drop_constraint(None, 'crtransaction', type_='foreignkey')
    # ### end Alembic commands ###
