"""empty message

Revision ID: 847678b885e3
Revises: d5ef342bd5f3
Create Date: 2020-12-02 11:20:04.113807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847678b885e3'
down_revision = 'd5ef342bd5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv', sa.Column('is_expense', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inv', 'is_expense')
    # ### end Alembic commands ###
