"""empty message

Revision ID: a27d68c3df33
Revises: 149ac8d8520c
Create Date: 2021-01-09 10:53:42.053122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27d68c3df33'
down_revision = '149ac8d8520c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loantransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('crtransaction', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crtransaction', 'customer', ['customer_id'], ['id'])
    op.add_column('customer', sa.Column('remaining_balance', sa.Float(), nullable=True))
    op.add_column('drtransaction', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drtransaction', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drtransaction', type_='foreignkey')
    op.drop_column('drtransaction', 'customer_id')
    op.drop_column('customer', 'remaining_balance')
    op.drop_constraint(None, 'crtransaction', type_='foreignkey')
    op.drop_column('crtransaction', 'customer_id')
    op.drop_table('loantransaction')
    # ### end Alembic commands ###
