"""empty message

Revision ID: acc4d48379be
Revises: 3aeea2af3779
Create Date: 2020-11-30 11:52:07.703664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc4d48379be'
down_revision = '3aeea2af3779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv', sa.Column('initiator', sa.String(length=64), nullable=True))
    op.add_column('inv', sa.Column('is_refunded', sa.Boolean(), nullable=True))
    op.add_column('inv', sa.Column('refund_amount', sa.Float(), nullable=True))
    op.create_index(op.f('ix_inv_initiator'), 'inv', ['initiator'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inv_initiator'), table_name='inv')
    op.drop_column('inv', 'refund_amount')
    op.drop_column('inv', 'is_refunded')
    op.drop_column('inv', 'initiator')
    # ### end Alembic commands ###
