"""empty message

Revision ID: b72419c59f0b
Revises: c0ec58b4c78a
Create Date: 2020-11-17 19:48:18.394606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72419c59f0b'
down_revision = 'c0ec58b4c78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crtransaction', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crtransaction', 'inv', ['invoice_id'], ['id'])
    op.add_column('drtransaction', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drtransaction', 'inv', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drtransaction', type_='foreignkey')
    op.drop_column('drtransaction', 'invoice_id')
    op.drop_constraint(None, 'crtransaction', type_='foreignkey')
    op.drop_column('crtransaction', 'invoice_id')
    # ### end Alembic commands ###
