"""empty message

Revision ID: bac955dae5ff
Revises: c5db78a6d9bf
Create Date: 2021-01-09 11:57:18.809355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac955dae5ff'
down_revision = 'c5db78a6d9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'crtransaction', 'customer', ['customer_id'], ['id'])
    op.add_column('customer', sa.Column('remaining_balance', sa.Float(), nullable=True))
    op.drop_constraint(None, 'revtransaction', type_='foreignkey')
    op.drop_column('revtransaction', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revtransaction', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'revtransaction', 'customer', ['customer_id'], ['id'])
    op.drop_column('customer', 'remaining_balance')
    op.drop_constraint(None, 'crtransaction', type_='foreignkey')
    # ### end Alembic commands ###
