"""empty message

Revision ID: bbafad68f602
Revises: 0842e999a163
Create Date: 2020-11-20 18:54:33.611266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbafad68f602'
down_revision = '0842e999a163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inv_inv_type'), 'inv', ['inv_type'], unique=False)
    op.create_index(op.f('ix_inv_status'), 'inv', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inv_status'), table_name='inv')
    op.drop_index(op.f('ix_inv_inv_type'), table_name='inv')
    # ### end Alembic commands ###
