"""empty message

Revision ID: be96089c4f31
Revises: 56db5ca97854
Create Date: 2020-11-20 10:29:26.751793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be96089c4f31'
down_revision = '56db5ca97854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inv', sa.Column('total', sa.Float(), nullable=True))
    op.add_column('inv', sa.Column('vat_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inv', 'vat_value')
    op.drop_column('inv', 'total')
    op.drop_table('vat')
    # ### end Alembic commands ###
