"""empty message

Revision ID: c0ec58b4c78a
Revises: 
Create Date: 2020-10-21 22:04:29.364643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ec58b4c78a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_invoice',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.add_column('transaction', sa.Column('description', sa.String(length=64), nullable=True))
    op.add_column('transaction', sa.Column('total', sa.Float(), nullable=True))
    op.drop_column('transaction', 'dwscription')
    op.drop_column('transaction', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('transaction', sa.Column('dwscription', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('transaction', 'total')
    op.drop_column('transaction', 'description')
    op.drop_table('product_invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
