"""empty message

Revision ID: dc2954e971cb
Revises: bbafad68f602
Create Date: 2020-11-30 00:03:51.980050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2954e971cb'
down_revision = 'bbafad68f602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_alike', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('branch1', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('branch2', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('warehouse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'warehouse')
    op.drop_column('user', 'branch2')
    op.drop_column('user', 'branch1')
    op.drop_column('user', 'admin_alike')
    # ### end Alembic commands ###
