"""empty message

Revision ID: f39b74c0df65
Revises: 16e5065ee545
Create Date: 2021-01-09 11:51:49.497020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39b74c0df65'
down_revision = '16e5065ee545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crtransaction', 'customer_id')
    op.add_column('customer', sa.Column('remaining_balance', sa.Float(), nullable=True))
    op.drop_constraint(None, 'revtransaction', type_='foreignkey')
    op.drop_column('revtransaction', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revtransaction', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'revtransaction', 'customer', ['customer_id'], ['id'])
    op.drop_column('customer', 'remaining_balance')
    op.add_column('crtransaction', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
